### PR TITLE
T/vmware

### PR DESCRIPTION
**Pull request by till**
Updates:

 * update Virtualbox vagrant box
 * added a VMware vagrant box
 * updated to packer template
 * added post-processors for Atlas
 * successfully build `imagineeasy/vagrant`
 * published boxes on Atlas: https://atlas.hashicorp.com/imagineeasy/boxes/vagrant

### CODE REVIEW

**Comment by till** [comment]
@fh Done!

**Comment by fh** [comment]
@till Cant test this, dont have vmware.

**Comment by till** [comment]
@fh `packer build -only=virtualbox-iso template.json`

**Comment by fh** [comment]
@till Can you flesh out the vmware parts, then, and assign those to someone else? I dont want to merge untested code.

**Comment by till** [comment]
@fh No one is using it yet as it's not exactly production ready. I just tried both boxes on the bib-cd branch and they work. If you are okay. I will merge this myself.

**Comment by till** [comment]
@fh Both boxes are published: https://atlas.hashicorp.com/imagineeasy/boxes/vagrant

**Pull request merged**
